In [158]:

import pandas as pd
import os
import numpy as np


In [206]:
df=pd.read_csv("autos_dataset.csv") 
df[["length","width","height","curb-weight"]]
df

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19     3.4              10.0        102   
4            136         mpfi  3.19     3.4               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01     3.4              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

# user test function

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   aspiration         205 non-null    object 
 5   num-of-doors       205 non-null    object 
 6   body-style         205 non-null    object 
 7   drive-wheels       205 non-null    object 
 8   engine-location    205 non-null    object 
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object 
 15  num-of-cylinders   205 non-null    object 
 16  engine-size        205 non

In [161]:
['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price']

['symboling',
 'normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'peak-rpm',
 'city-mpg',
 'highway-mpg',
 'price']

In [162]:
df.tail(1).values

array([[-1, '95', 'volvo', 'gas', 'turbo', 'four', 'sedan', 'rwd',
        'front', 109.1, 188.8, 68.9, 55.5, 3062, 'ohc', 'four', 141,
        'mpfi', '3.78', '3.15', 9.5, '114', '5400', 19, 25, '22625']],
      dtype=object)

In [163]:
import pickle

In [164]:
with open("firstmodel.pkl","rb") as file:
    model=pickle.load(file)

In [174]:
import json
with open("columns.json","r") as file:
    columns_name=json.load(file)
    columns_name["columns"]
user_input=np.zeros(len(columns_name["columns"]))
arr_col=np.array(columns_name["columns"])
arr_col

array(['symboling', 'normalized-losses', 'fuel-type', 'aspiration',
       'num-of-doors', 'engine-location', 'wheel-base', 'length', 'width',
       'height', 'curb-weight', 'num-of-cylinders', 'engine-size', 'bore',
       'stroke', 'compression-ratio', 'horsepower', 'peak-rpm',
       'city-mpg', 'highway-mpg', 'make_alfa-romero', 'make_audi',
       'make_bmw', 'make_chevrolet', 'make_dodge', 'make_honda',
       'make_isuzu', 'make_jaguar', 'make_mazda', 'make_mercedes-benz',
       'make_mercury', 'make_mitsubishi', 'make_nissan', 'make_peugot',
       'make_plymouth', 'make_porsche', 'make_renault', 'make_saab',
       'make_subaru', 'make_toyota', 'make_volkswagen', 'make_volvo',
       'body-style_convertible', 'body-style_hardtop',
       'body-style_hatchback', 'body-style_sedan', 'body-style_wagon',
       'dw_4wd', 'dw_fwd', 'dw_rwd', 'engine-type_dohc',
       'engine-type_dohcv', 'engine-type_l', 'engine-type_ohc',
       'engine-type_ohcf', 'engine-type_ohcv', 'engine-t

In [166]:
user_input

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [167]:

#print(f"{data=}")
price=model.predict([user_input])
print(f"predicted price={price}")

predicted price=[-64437.58372631]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [168]:
with open("Encoded_data.json","r") as file:
    encoaded_data=json.load(file)
print(encoaded_data)    

    

{'fuel_type': {'gas': 0, 'diesel': 1}, 'aspiration': {'std': 0, 'turbo': 1}, 'num_of_doors': {'four': 4, 'two': 2}, 'engine_location': {'front': 0, 'rear': 1}, 'num_of_cylinders': {'four': 4, 'six': 6, 'five': 5, 'eight': 8, 'two': 2, 'three': 3, 'twelve': 12}}


In [176]:
symboling=-1
normalized_losses=95
make="volvo"
fuel_type="gas"
aspiration="turbo"
num_of_doors="four"
body_style="sedan"
drive_wheels="rwd"
engine_location="front"
wheel_base=109.1
length=188.8
width=68.9
height=55.5
curb_weight=3062
engine_type="ohc"
num_of_cylinders="four"
engine_size=141
fuel_system="mpfi"
bore=3.78
stroke=3.15
compression_ratio=9.5
horsepower=114
peak_rpm=5400
city_mpg=19
highway_mpg=25

user_input[0]=symboling

user_input[1]=normalized_losses

# if fuel_type="gas":
#     user_input[2]=0
# else:
#     user_input[2]=1
#or
user_input[2]=encoaded_data["fuel_type"][fuel_type]    
user_input[3]=encoaded_data["aspiration"][aspiration]       # for lebel encoaded data
user_input[4]=encoaded_data["num_of_doors"][num_of_doors]  
user_input[5]=encoaded_data["engine_location"][engine_location]  
user_input[6]=wheel_base# for integer data
user_input[7]=length
user_input[8]=width
user_input[9]=height
user_input[10]=curb_weight
user_input[11]=encoaded_data["num_of_cylinders"][num_of_cylinders]
user_input[12]=engine_size
user_input[13]=bore
user_input[14]=stroke
user_input[15]=compression_ratio
user_input[16]=horsepower
user_input[17]=peak_rpm
user_input[18]=city_mpg
user_input[19]=highway_mpg


# make_string = 'make_'+make
# make_index = np.where(array == make_string)[0][0]
# user_input[make_index] = 1 

make_search_string="make_"+make                                    # for one hot encoaded data
index1=np.where(arr_col==make_search_string)[0][0]
user_input[index1]=1

# body_style_search_string="body_style_"+body_style
# index2=np.where(arr_col==body_style_search_string)[0][0]
# user_input[index2]=1
body_style_string ="body-style_"+body_style
bs_index = np.where(arr_col== body_style_string)[0][0]
user_input[bs_index] = 1

drive_wheels_search_string="dw_"+drive_wheels             # for one hot encoaded data
index=np.where(arr_col==drive_wheels_search_string)[0][0]
user_input[index]=1

engine_type_search_string="engine-type_"+engine_type              
index=np.where(arr_col==engine_type_search_string)[0][0]
user_input[index]=1

fuel_system_style_search_string="fuel-system_"+fuel_system
index=np.where(arr_col==fuel_system_style_search_string)[0][0]
user_input[index]=1

# data=[symboling, normalized_losses, make, fuel_type, aspiration,
#        num_of_doors, body_style, drive_wheels, engine_location,
#        wheel_base, length, width, height, curb_weight, engine-type,
#        num_of_cylinders, engine_size, fuel_system, bore, stroke,
#        compression_ratio, horsepower, peak_rpm, city_mpg,
#        highway_mpg, price]

In [177]:
data=user_input
data


array([-1.000e+00,  9.500e+01,  0.000e+00,  1.000e+00,  4.000e+00,
        0.000e+00,  1.091e+02,  1.888e+02,  6.890e+01,  5.550e+01,
        3.062e+03,  4.000e+00,  1.410e+02,  3.780e+00,  3.150e+00,
        9.500e+00,  1.140e+02,  5.400e+03,  1.900e+01,  2.500e+01,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00])

In [178]:

print(f"{data=}")
price=model.predict([data])
print(f"predicted price={price}")

data=array([-1.000e+00,  9.500e+01,  0.000e+00,  1.000e+00,  4.000e+00,
        0.000e+00,  1.091e+02,  1.888e+02,  6.890e+01,  5.550e+01,
        3.062e+03,  4.000e+00,  1.410e+02,  3.780e+00,  3.150e+00,
        9.500e+00,  1.140e+02,  5.400e+03,  1.900e+01,  2.500e+01,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00])
predicted price=[20569.76387688]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
